name = "cloudrealty-crm"
compatibility_date = "2024-09-25"
main = "functions/_worker.ts"
pages_build_output_dir = "dist"
assets = { directory = "dist" }

[vars]
JWT_SECRET = "dev-secret-change-in-production"

[[d1_databases]]
binding = "DB"
database_name = "cloudrealty-crm-db"
database_id = "b864af26-b2c4-4906-b035-24f929a91e9a"
